import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// component
import Layout from "../components/templates/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`my-[60px] lg:my-[0px] lg:mr-[60px] ${inter.className}`}
        suppressHydrationWarning={true}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
